development:
  adapter: postgresql
  encoding: unicode
  database: fta_development
  username: binitkumar
  pool: 5
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: fta_test
  username: binitkumar
  pool: 5
  host: localhost
  port: 5432
